// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTabOa37YL1o4mRem7PSTwcyr1_g64tI',
    appId: '1:644645909557:web:4572dc46a472af1688ad7c',
    messagingSenderId: '644645909557',
    projectId: 'ipark-cf215',
    authDomain: 'ipark-cf215.firebaseapp.com',
    storageBucket: 'ipark-cf215.appspot.com',
    measurementId: 'G-3NLS4VRQRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-TTKKBBq4ZHv0f8fBzyh2R4laUs2Kq4',
    appId: '1:644645909557:android:e8fb5f774a82cb9c88ad7c',
    messagingSenderId: '644645909557',
    projectId: 'ipark-cf215',
    storageBucket: 'ipark-cf215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrdArJ7Ecc15hqLxSbFozmGoJ4ndx5yJk',
    appId: '1:644645909557:ios:7f5f9a5abf413d0e88ad7c',
    messagingSenderId: '644645909557',
    projectId: 'ipark-cf215',
    storageBucket: 'ipark-cf215.appspot.com',
    iosClientId: '644645909557-d45k15corop9cs85ttd395mo46eeepb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrdArJ7Ecc15hqLxSbFozmGoJ4ndx5yJk',
    appId: '1:644645909557:ios:7f5f9a5abf413d0e88ad7c',
    messagingSenderId: '644645909557',
    projectId: 'ipark-cf215',
    storageBucket: 'ipark-cf215.appspot.com',
    iosClientId: '644645909557-d45k15corop9cs85ttd395mo46eeepb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipark',
  );
}
